### ISSUE TITLE
Increased CPU usage

### ISSUE THREAD

**Issue by thim81** [mountainash/Mixcloud-Play#105]
Hi @mountainash 

Thanks for all the great work on keeping the Mac Mixcloud app in such great shape.

I installed the latest version [v0.19.0](https://github.com/mountainash/Mixcloud-Play/tree/v0.19.0) for a Apple M1 Pro.
While just playing normal music the CPU usage for Mixcloud is around 64% continuously.

Not sure if it was that high before, but wanted to report it for awareness.

**Comment by mountainash** [comment]
That seems very excessive! I have the same hardware and didn't notice anything (but I wasn't checking). I'll take a look and see what I can do. Thanks for reporting it.

**Comment by mountainash** [comment]
Hello @thim81 - please try the [latest release](https://github.com/mountainash/Mixcloud-Play/releases/) and see if that improves things for you. On my M1 Pro I'm seeing ~15-16% CPU Usage when playing music and less that 1% when not.

<img width="1258" alt="Screenshot showing CPU usage" src="https://github.com/mountainash/Mixcloud-Play/assets/27637/621b8a3d-e065-4089-b79f-39094bc2f3ae">

**Comment by thim81** [comment]
hi @mountainash 

Thanks for taking the time to keep the MixCloud App up-to-date. It is my most used music app, so I'm happy user.
I'll give the new version a spin next week and close the issue.

**Comment by thim81** [comment]
Questions:
- is it possible the ARM64 DMG is not released?
- I cant login in the new version, do you experienced the same?

**Comment by mountainash** [comment]
Thank you for the kind words- It's nice knowing it's been used.

- ARM64 files have been added to the release, please check again
- Good find - this is a bug. Workaround: click "Join" and then the "login" tab in the modal

**Comment by thim81** [comment]
The CPU load never goes above 26%, so closing this issue.
![IMG 2024-09-16 at 11 51 13@2x](https://github.com/user-attachments/assets/bc105bd4-8435-4678-bc87-d73ab5860224)
