### ISSUE TITLE
Drag behaviour

### ISSUE THREAD

**Issue by thim81** [mountainash/Mixcloud-Play#34]
Hi Ash,

I love what your doing with the Mixcloud play app, the auto-updater, the media keys support, ...
I just got the latest update and it is working perfect!

I have noticed one change that is behaving strange:
- In the player queue, you could drag items to change the order
- In the search, when trying to move the cursor
==> all result in the full application window being dragged instead of the queue item or cursor

I'm not running MixCloud-play full screen but windowed, perhaps this is the reason?

If you want more info, let me know, so I can record a screen capture to show the behavior.

Regards,
Tim

**Comment by thim81** [comment]
Could it be related to?
https://www.electronjs.org/docs/api/frameless-window#draggable-region

**Comment by mountainash** [comment]
Thanks for raising the issue @thim81. I've fixed this in the code and will package it in the next release (maybe tomorrow).

And thanks for the positive feedback - I'm surprised anyone still using this, it would be pretty hard to find this 2nd level fork.

**Comment by thim81** [comment]
I'm a big fan of MixCloud but the browser experience is just not the same as a real music player like iTunes. The Android/iOS app on the other hand is a music playing app. And the mixcloud-play app fills that spot, due it the nice integration of the media keys, notifications, seperate window, ...

So I'm a big fan of your improvements, so please keep on improving 🥇 
I just updated to the latest version and I can confirm the dragging options are back. Great job!!!
