### ISSUE TITLE
Main download is not the lastest version

### ISSUE THREAD

**Issue by orange-87** [mountainash/Mixcloud-Play#38]
Hi!
I've just gona to try your app but when I've installed from main site "https://github.com/uffou/MixCloud-Play > Download for Mac" the downloaded version is 0.0.1 but not the last you have uploaded (0.0.16) in "https://github.com/mountainash/Mixcloud-Play/releases"
Consecuently I've tried several times reinstalling and deleting app in my Mac and doubting where the problem is...

Please fix it :)

![Captura de pantalla 2020-04-21 a las 23 53 08](https://user-images.githubusercontent.com/62965963/79917906-b72f1e00-842b-11ea-8a38-dbab9d4d4987.png)

**Comment by mountainash** [comment]
That's an issue for the root/parent project... https://github.com/uffou/MixCloud-Play

Can you raise the issue there the maintainer of that repository?
