### ISSUE TITLE
Update dependencies

### ISSUE THREAD

**Issue by mountainash** [mountainash/Mixcloud-Play#44]
There are many outdated dependencies ([raised as pull requests](https://github.com/mountainash/Mixcloud-Play/pulls/app%2Frenovate)) that need to be upgraded and then the app tested to see it still works, before marking the merge for approval.

**Comment by Kishore-abhimanyu** [comment]
can you assign this to me?

**Comment by mountainash** [comment]
Sure, but please note the testing aspect of this task. Need to check all features still work as expected after updating the dependencies.

**Comment by Kishore-abhimanyu** [comment]
This issue is fixed, can you check and merge it?

**Comment by mountainash** [comment]
That's for looking into this @Kishore-abhimanyu, but the commit only includes a change to one minor dependency. The task is to go through each of the primary dependencies for this project that have been raised by @renovate-app as out of date. You can see these here: https://github.com/mountainash/Mixcloud-Play/pulls/app%2Frenovate

You should be able to run `npm update` over the project to pull the updates. Then attempt to build Mixcloud-Play as test it's all working to the same (or better) standard of the current release version.

**Comment by mountainash** [comment]
All Renovate dependency updates have be done in a0ccc5, but Electron is still at v3.1.13, but I'll go through each major release now and see how high we can get before things break.

**Comment by mountainash** [comment]
I was able to update to Electron v4.2.12 but v5.0.12 and even v5.0.0 fail (= media keys don't work, notifications don't work, and menubar doesn't show tracks).
