### ISSUE TITLE
Can't login via Facebook button

### ISSUE THREAD

**Issue by lastbreak** [mountainash/Mixcloud-Play#59]
**This the bug that I get**:
When I try to login via facebook login the popup window to the facebook opens but closes instantly.

This project it's very promising and so far I'm enjoying it...thanks for the developers for their work. If it's allowed here, I also would like to ask for a new feature...I'm a linux user as well and would be great to use this app on debian and arch based distribuitions.

**Comment by mountainash** [comment]
Thanks for the feedback @lastbreak. Should be an easy fix - I'll do an update soon.

I've raised your Linux version request in a new issue - #60

**Comment by mountainash** [comment]
@lastbreak the Facebook login issue should be fixed now if you'd like to try again.

Their should be no issues to build the project for Linux (and derivatives): see https://www.electron.build/configuration/linux#LinuxConfiguration-target for the output options available to build. I only have a Mac so I'm unable to test all the alternatives - give it a try:
```bash
git clone git@github.com:mountainash/Mixcloud-Play.git
cd Mixcloud-Play
npm install
[modify the package.js with the desired targets]
npm run build
```
